name: civilistica
favicon: null
layout_spectrum: 0.7928627885412425
typography_spectrum: 0.13607212132774293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221715'
    - '#fd4a08'
    - '#821d79'
    - '#7c5b94'
    - '#a28f95'
  brandStrength: 0.4933751826174557
  lightness: 0.24956135265529156
  saturation: 0.3016741389874369
  rhythmicContrast: 0.41715887817554176
purpose: []
